os:
  - ubuntu/trusty64
cassandra:
  - 2.0
  - 2.1
  - 2.2
  - 3.0
  - '3.10'
env:
  CSHARP_VERSION:
    - netcore
build:
  - script: |
      # Set the Java paths (for CCM)
      export JAVA_HOME=$CCM_JAVA_HOME
      export PATH=$JAVA_HOME/bin:$PATH

      # Define Cassandra runtime
      echo "==========setting cassandra version=========="
      export CASSANDRA_VERSION=$CCM_CASSANDRA_VERSION
      export SCASSANDRA_JAR=$HOME/scassandra-server_2.11-1.0.10-standalone.jar 

      echo "==========copying ssl files to $HOME/ssl=========="
      cp -r /home/jenkins/ccm/ssl $HOME/ssl
 
      # Install the required packages
      dotnet restore src

      # Run the tests
      echo "==========RUNNING FULL SUITE OF TESTS=========="
      #dotnet test src/Cassandra.IntegrationTests/Cassandra.IntegrationTests.csproj -f netcoreapp1.0 -c Release --filter TestCategory=short --logger "trx;LogFileName=../../../TestResult_xunit.xml"
      dotnet test src/Cassandra.IntegrationTests/Cassandra.IntegrationTests.csproj -f netcoreapp1.0 -c Release --filter Name=QueryBinding --logger "trx;LogFileName=../../../TestResult_xunit.xml"
      saxon-xslt -o TestResult.xml TestResult_xunit.xml tools/nunit3-xunit.xslt
  - xunit:
    - "TestResult.xml"

