os:
  - ubuntu/bionic64/csharp-driver
cassandra:
  - 2.1
  - 2.2
  - 3.0
  - '3.11'
env:
  CSHARP_VERSION:
    - mono
    - netcore
build:
  - script: |
      # Set the Java paths (for CCM)
      export JAVA_HOME=$CCM_JAVA_HOME
      export PATH=$JAVA_HOME/bin:$PATH
      export SIMULACRON_PATH=$HOME/simulacron.jar

      # Define Cassandra runtime
      echo "==========setting cassandra version=========="
      export CASSANDRA_VERSION=$CCM_CASSANDRA_VERSION

      echo "==========copying ssl files to $HOME/ssl=========="
      cp -r /home/jenkins/ccm/ssl $HOME/ssl
 
      if [ $CSHARP_VERSION = 'mono' ]; then
          echo "==========csharp verion mono=========="
          # Define alias for Nuget
          nuget() {
                mono /home/jenkins/nuget/NuGet.exe "$@"
          }
          export -f nuget
          # Install the required packages
          export EnableNuGetPackageRestore=true
          msbuild /t:restore /v:m src/Cassandra.sln
          nuget install NUnit.Runners -Version 3.6.1 -OutputDirectory testrunner
          # Compile the driver and test code
          msbuild /p:Configuration=Release /v:m /p:DynamicConstants=LINUX src/Cassandra.sln
          # Run the tests
          echo "==========RUNNING FULL SUITE OF TESTS=========="
          mono ./testrunner/NUnit.ConsoleRunner.3.6.1/tools/nunit3-console.exe src/Cassandra.IntegrationTests/bin/Release/net452/Cassandra.IntegrationTests.dll --where:cat=short --labels=All --result:"TestResult_nunit3.xml"
          saxon-xslt -o TestResult.xml TestResult_nunit3.xml tools/nunit3-xunit.xslt
      else
          # Install the required packages
          dotnet restore src

          # Run the tests
          echo "==========RUNNING FULL SUITE OF TESTS=========="
          dotnet test src/Cassandra.IntegrationTests/Cassandra.IntegrationTests.csproj -f netcoreapp1.0 -c Release --filter TestCategory=short --logger "trx;LogFileName=../../../TestResult_trx.xml"
          saxon-xslt -o TestResult.xml TestResult_trx.xml tools/trx-to-junit.xslt
      fi

  - xunit:
    - "TestResult.xml"

