schedules:
  commit-dse:
    # Run short suite on commit
    schedule: per_commit
    notify:
      slack: csharp-driver-dev-bots
    matrix:
      exclude:
      # on linux with netcoreapp2.1 target dse-5.1 and dse-6.7
        - os: 'ubuntu/bionic64/csharp-driver'
          dotnet: ['netcoreapp2.1']
          cassandra: ['dse-5.0', 'dse-6.0', 'dse-6.8.0']
      # on linux with mono and netcoreapp2.0 target dse-6.7
        - os: 'ubuntu/bionic64/csharp-driver'
          dotnet: ['mono', 'netcoreapp2.0']
          cassandra: ['dse-5.0', 'dse-5.1', 'dse-6.0', 'dse-6.8.0']
  nightly-dse-ubuntu:
    # nightly job for primary branches to run almost all configs on ubuntu.
    schedule: nightly
    notify:
      slack: csharp-driver-dev-bots
    branches:
      # regex matches primary branch format (2.1, 3.x, 3.0.x, 3.1.x, master, etc).
      include: ["/((\\d+(\\.[\\dx]+)+)|master)/"]
    matrix:
      exclude:
      # on linux with netcoreapp2.1 target all dse
      # on linux with mono and netcoreapp2.0 target dse-5.1, dse-6.7 and dse-6.8.0
        - os: 'ubuntu/bionic64/csharp-driver'
          dotnet: ['mono', 'netcoreapp2.0']
          cassandra: ['dse-5.0', 'dse-6.0']
  adhoc:
    # adhoc job for non-primary braches that doesn't have the nightly and weekly schedules so this may be used to run same configs as the weekly schedule.
    schedule: adhoc
    notify:
      slack: csharp-driver-dev-bots
    branches:
      exclude: ["/((\\d+(\\.[\\dx]+)+)|master)/"]
  weekly:
    schedule: 0 10 * * 7
    notify:
      slack: csharp-driver-dev-bots
    branches:
      include: ["/((\\d+(\\.[\\dx]+)+)|master)/"]
os:
  - ubuntu/bionic64/csharp-driver
cassandra:
  - 'dse-5.0'
  - 'dse-5.1'
  - 'dse-6.0'
  - 'dse-6.7'
  - 'dse-6.8.0'
dotnet:
  - 'mono'
  - 'netcoreapp2.0'
  - 'netcoreapp2.1'
build:
  - script: |
      export CASS_VERSION_SNI='dse-6.7'
       
      # Set the Java paths (for CCM)
      export JAVA_HOME=$CCM_JAVA_HOME
      export PATH=$JAVA_HOME/bin:$PATH
      export SIMULACRON_PATH=$HOME/simulacron.jar

      if [[ $CASSANDRA_VERSION == dse-* ]] ;
      then
          export CCM_PATH=$HOME/ccm
          export DSE_BRANCH=$CCM_BRANCH
          export DSE_VERSION=$CCM_VERSION
          export DSE_INITIAL_IPPREFIX="127.0.0."
          export DSE_IN_REMOTE_SERVER="false"
                
          if [ $DSE_VERSION = '6.0' ]; then
              echo "Setting DSE 6.0 install-dir"
              export DSE_PATH=$CCM_INSTALL_DIR
          fi
          
          echo $DSE_VERSION
          echo $DSE_PATH
          echo $DSE_INITIAL_IPPREFIX
          echo $DSE_IN_REMOTE_SERVER
          echo $DSE_INITIAL_IPPREFIX
      fi

      echo $CSHARP_VERSION

      # Define Cassandra runtime
      echo "========== Setting Server Version =========="
      export CASSANDRA_VERSION_ORIGINAL=$CASSANDRA_VERSION
      export CASSANDRA_VERSION=$CCM_CASSANDRA_VERSION

      echo "========== Copying ssl files to $HOME/ssl =========="
      cp -r /home/jenkins/ccm/ssl $HOME/ssl
      
      if [ $CASSANDRA_VERSION_ORIGINAL = $CASS_VERSION_SNI ]; then  
          export SNI_ENABLED="true"
          export SINGLE_ENDPOINT_PATH="${HOME}/proxy/run.sh"
          export SNI_CERTIFICATE_PATH="${HOME}/proxy/certs/client_key.pfx"
          export SNI_CA_PATH="${HOME}/proxy/certs/root.crt"
      fi
      
      echo $SNI_ENABLED
      echo $SINGLE_ENDPOINT_PATH
      echo $SNI_CERTIFICATE_PATH
      echo $SNI_CA_PATH
      
      ls "${HOME}/proxy/" 

      # Download and uncompress saxon
      mkdir saxon
      curl -L -o saxon/saxon9he.jar https://repo1.maven.org/maven2/net/sf/saxon/Saxon-HE/9.8.0-12/Saxon-HE-9.8.0-12.jar
 
      if [ $DOTNET_VERSION = 'mono' ]; then      
          echo "========== Starting Mono Build =========="
          mono --version
          # Define alias for Nuget
          nuget() {
                mono /usr/local/bin/nuget.exe "$@"
          }
          export -f nuget

          # Install the required packages
          nuget install NUnit.Runners -Version 3.6.1 -OutputDirectory testrunner

          # Compile the driver and test code
          msbuild /t:restore /v:m src/Dse.sln
          msbuild /p:Configuration=Release /v:m /p:DynamicConstants=LINUX src/Dse.sln

          # Run the tests
          mono ./testrunner/NUnit.ConsoleRunner.3.6.1/tools/nunit3-console.exe src/Dse.Test.Integration/bin/Release/net452/Dse.Test.Integration.dll --where "cat != long && cat != memory" --labels=All --result:"TestResult_nunit.xml" || error=true
          java -jar saxon/saxon9he.jar -o:TestResult.xml TestResult_nunit.xml tools/nunit3-junit.xslt
          
          #Fail the build if there was an error
          if [ $error ]
          then 
              exit -1
          fi
      else
          echo "========== Starting .NET Core Build =========="
          export DOTNET_CLI_TELEMETRY_OPTOUT=1
          dotnet --version

          # Install the required packages
          dotnet restore src

          # Run the tests
          dotnet test src/Dse.Test.Integration/Dse.Test.Integration.csproj -v n -f $DOTNET_VERSION -c Release --filter "(TestCategory!=long)&(TestCategory!=memory)" --logger "xunit;LogFilePath=../../TestResult_xunit.xml" || error=true
          java -jar saxon/saxon9he.jar -o:TestResult.xml TestResult_xunit.xml tools/JUnitXml.xslt
          
          #Fail the build if there was an error
          if [ $error ]
          then 
              exit -1
          fi
      fi
      

  - xunit:
    - "**/TestResult.xml"

