//
//      Copyright (C) DataStax Inc.
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
//

using System;

namespace Cassandra.SessionManagement
{
    /// <inheritdoc cref="IDseSession"/>
    /// <remarks>This is an internal interface designed to declare the internal methods that are called
    /// across multiple locations of the driver's source code. Similar to <see cref="IInternalSession"/> but
    /// this interface extends <see cref="IDseSession"/></remarks>
    internal interface IInternalDseSession : IDseSession, IInternalSession
    {
        /// <summary>
        /// Unique Session ID generated by the driver.
        /// </summary>
        Guid InternalSessionId { get; }
    }
}