//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyCompany("DataStax")]
[assembly: System.Reflection.AssemblyProduct("DataStax Enterprise Driver")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Reflection.AssemblyCopyright("Copyright © 2016 by DataStax")]
[assembly: System.Reflection.AssemblyVersion("1.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("1.0.0-eap1 (git 3362bfd)")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.0.0")]


