//
//  Copyright (C) 2017 DataStax, Inc.
//
//  Please see the license for details:
//  http://www.datastax.com/terms/datastax-dse-driver-license-terms
//

using System;

namespace Dse.SessionManagement
{
    /// <inheritdoc cref="IDseSession"/>
    /// <remarks>This is an internal interface designed to declare the internal methods that are called
    /// across multiple locations of the driver's source code. Similar to <see cref="IInternalSession"/> but
    /// this interface extends <see cref="IDseSession"/></remarks>
    internal interface IInternalDseSession : IDseSession, IInternalSession
    {
        /// <summary>
        /// Unique Session ID generated by the driver.
        /// </summary>
        Guid InternalSessionId { get; }
    }
}