//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyCompany("DataStax")]
[assembly: System.Reflection.AssemblyProduct("DataStax C# Driver EntityContext")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Reflection.AssemblyCopyright("Copyright © 2014 by DataStax")]
[assembly: System.Reflection.AssemblyVersion("2.1.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("2.1.0 (git 594cf56)")]
[assembly: System.Reflection.AssemblyFileVersion("2.1.0.200")]


