//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyCompany("DataStax")]
[assembly: System.Reflection.AssemblyProduct("Cassandra .NET Driver")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Reflection.AssemblyCopyright("Copyright © 2015 by DataStax")]
[assembly: System.Reflection.AssemblyVersion("2.5")]
[assembly: System.Reflection.AssemblyInformationalVersion("2.5.2 (git 8a3e75c)")]
[assembly: System.Reflection.AssemblyFileVersion("2.5.2.0")]


