//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyCompany("DataStax")]
[assembly: System.Reflection.AssemblyProduct("Cassandra .NET Driver")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Reflection.AssemblyCopyright("Copyright © 2016 by DataStax")]
[assembly: System.Reflection.AssemblyVersion("3.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("3.0.9 (git 5ca22bb)")]
[assembly: System.Reflection.AssemblyFileVersion("3.0.9.0")]


